apiVersion: v1
kind: Service
metadata:
  name: my-sample-server
spec:
  ports:
  - port: 80
    targetPort: 1337 
    protocol: TCP
    name: my-sample-server
  type: NodePort 
  selector:
    app: my-sample-server   